credentials:
  usernames:
    fpeerzade:
      email: fayequepeerzade@gmail.com
      failed_login_attempts: 0
      logged_in: False
      name: Fayeque Peerzade
      password: Fayeque@P1104
cookie:
  expiry_days: 0
  key: some_signature_key
  name: some_cookie_name
pre-authorized:
  emails:
  - melsby@gmail.com
theme:
  base="dark"
  primaryColor="#00bdd6"

